<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <ProjectReference Include="..\ECommerce.Application\ECommerce.Application.csproj"/>
        <ProjectReference Include="..\ECommerce.Infrastructure\ECommerce.Infrastructure.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

</Project>
